" Vim configuration by Lubomir-Russia
" Settings are gathered from different books, sites, and people
"
" Installation :
" Copy or symlink to ~/.vimrc or ~/_vimrc. and make dir for swap files
" ln -nfs ~/bin/dotfiles/vim/vimrc ~/.vimrc
" ln -nfs ~/bin/dotfiles/vim ~/.vim
" mkdir -p ~/.bak/swap

set nocompatible                  " Must come first because it changes other options.

silent! call pathogen#runtime_append_all_bundles()

" Professor VIM says '87% of users prefer jj over esc', jj abrams disagrees
imap jj <Esc> 

" Mappings useful for log view
nmap <F3> /<<< ------<CR>zz 
nmap <F4> /START<CR>zt

" Mappings useful for Perl view
nmap <F5> :set number!<Cr>
nmap <F6> :set list!<Cr>
nmap <F8> :set wrap!<Cr>

" Mapping F7 for spell check (use ]s, z=, zg, zb)
nmap <F7> :set spell!<Cr>

" Tab mappings.
map <leader>tt :tabnew<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>to :tabonly<cr>
" useless, use default gt
" map <leader>tn :tabnext<cr>      
" useless, use default gT
" map <leader>tp :tabprevious<cr>  
map <leader>tf :tabfirst<cr>
map <leader>tl :tablast<cr>
map <leader>tm :tabmove

" Uncomment to use Jamis Buck's file opening plugin
"map <Leader>t :FuzzyFinderTextMate<Enter>

" Controversial...swap colon and semicolon for easier commands
"nnoremap ; :
"nnoremap : ;

"vnoremap ; :
"vnoremap : ;

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

runtime macros/matchit.vim        " Load the matchit plugin.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
" set wildmode=list:longest         " Complete files like a shell.
set wildmode=list,full            "	List all matches without completing, then each full match.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

" set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.bak/swap//,.  " Keep swap files in one location

set tabstop=4                     " Global tab width.
set shiftwidth=4                  " And again, related.
set expandtab                     " Use spaces instead of tabs
set softtabstop=4		  " It feels like <Tab>s are being inserted, while in fact a mix of spaces and <Tab>s is used.  
set showtabline=2		  " Display tabs all of the time
" set showbreak=------>
set list listchars=precedes:<,extends:> " Set list listchars=tab: ,precedes:<,extends:>
set nolist			  " Do not show list till asked to do it

set laststatus=2                  " Show the status line all the time
" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{fugitive#statusline()}%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P

" colorscheme topfunky-light
" colorscheme vividchalk
colorscheme murphy

" Automatic fold settings for specific files. Uncomment to use.
" autocmd FileType ruby setlocal foldmethod=syntax
" autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2

" To get basic Folding for Perl working add
let perl_fold=1
let perl_fold_blocks = 1


" For the MakeGreen plugin and Ruby RSpec. Uncomment to use.
" autocmd BufNewFile,BufRead *_spec.rb compiler rspec


